name: Or Condition Demo
on: push
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Run for Shalu or Shalu-Kone 
        if: github.actor == 'Shalu' || github.actor == 'Shalu-Kone' 
        run: echo "it is triggered by either Hari or Shalu-Kone"
    
       
    
