on:
  workflow_dispatch:
    branches:
      - feature/local_ciam
    paths:
      - 'auth0-user-migration/**'
      - '.github/workflows/**'
    inputs:
      environment:
        description: "Select environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - sit
          - prod

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        run: npm install

      - name: Run migration
        run: node migrate.js
        env:
          ENV: ${{ github.event.inputs.environment }}

          DEV_AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          DEV_AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          DEV_AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
          DEV_CONNECTION_ID: ${{ secrets.CONNECTION_ID }}

          SIT_AUTH0_DOMAIN: ${{ secrets.SIT_AUTH0_DOMAIN }}
          SIT_AUTH0_CLIENT_ID: ${{ secrets.SIT_AUTH0_CLIENT_ID }}
          SIT_AUTH0_CLIENT_SECRET: ${{ secrets.SIT_AUTH0_CLIENT_SECRET }}
          SIT_CONNECTION_ID: ${{ secrets.SIT_CONNECTION_ID }}

          PROD_AUTH0_DOMAIN: ${{ secrets.PROD_AUTH0_DOMAIN }}
          PROD_AUTH0_CLIENT_ID: ${{ secrets.PROD_AUTH0_CLIENT_ID }}
          PROD_AUTH0_CLIENT_SECRET: ${{ secrets.PROD_AUTH0_CLIENT_SECRET }}
          PROD_CONNECTION_ID: ${{ secrets.PROD_CONNECTION_ID }}
